# Generated by Django 5.2.5 on 2025-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='legend',
            field=models.CharField(default='no legend', max_length=255),
        ),
    ]
